"""empty message

Revision ID: 66c314fac6db
Revises: 1d7ea799563f
Create Date: 2026-09-02 19:50:26.985993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c314fac6db'
down_revision: Union[str, Sequence[str], None] = '1d7ea799563f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'SELLER', name='userrole'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('user_name_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_name_key'), 'user', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'role')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
